# Generated by Django 5.0.2 on 2024-02-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0002_alter_student_photo_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access',
            field=models.ManyToManyField(blank=True, null=True, to='trainingApp.course', verbose_name='Доступные курсы'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.course', verbose_name='Курс')),
                ('students', models.ManyToManyField(blank=True, null=True, to='trainingApp.student', verbose_name='Студенты')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAccess',
        ),
    ]
